[package]
name = "sqlite3_ext_demo_wnd"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sqlite3_ext = { version = "0.2.0", features = ["static"] }

[patch.crates-io]
sqlite3_ext = { git = "https://github.com/arianfarid/sqlite3_ext",
branch = "fix/windows-path-to-cstring" }
